os:
  - linux

language: go

go:
  - 1.11.x

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
